/*
* Autogenerated by Route Type Compiler (1.0.1)
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/

import ApiDemo from './api/demo';
import Demo from './demo';

declare module 'test' {
  const apiDemo: ApiDemo;
  const demo: Demo;
  export interface IGetRoute {
    'api/demo/': typeof apiDemo.alive,
    'api/demo/koa': typeof apiDemo.koa,
    'api/demo/error/path/somepath': typeof apiDemo.error,
    '/demo/': typeof demo.alive,
    '/demo/koa': typeof demo.koa,
    '/demo/error/path/somepath': typeof demo.error
  }
  export interface IPostRoute {
    'api/demo/koa': typeof apiDemo.koaPost,
    '/demo/koa': typeof demo.koaPost
  }
}
