"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const type_template_1 = require("./type_template");
const fs = require("fs-extra");
const path = require("path");
const process = require("process");
class TemplateEngine {
    constructor(filePathList, input, output) {
        this.output = output;
        this.templatePool = type_template_1.default(filePathList, input);
    }
    compile(moduleName, version) {
        const template = this.getTemplate(moduleName, version);
        const typeFilePath = path.join(process.cwd(), this.output, './index.d.ts');
        fs.ensureFileSync(typeFilePath);
        fs.writeFileSync(typeFilePath, template);
    }
    getTemplate(moduleName, version) {
        return `${this.getHeadCommet(version)}

${this.importTemplate}

${this.getModuleTemplate(moduleName)}`;
    }
    getHeadCommet(version) {
        this.output;
        return `/*
* Autogenerated by Route Type Compiler (${version})
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/`;
    }
    get importTemplate() {
        return this.templatePool.importPool.join('\n');
    }
    get instanceTemplate() {
        return this.templatePool.instancePool.join('\n  ');
    }
    get getRouteTemplate() {
        return this.templatePool.getRoutePool.join(',\n    ');
    }
    get postRouteTemplate() {
        return this.templatePool.postRoutePool.join(',\n    ');
    }
    getModuleTemplate(moduleName) {
        return `declare module '${moduleName}' {
  ${this.instanceTemplate}
  export interface IGetRoute {
    ${this.getRouteTemplate}
  }
  export interface IPostRoute {
    ${this.postRouteTemplate}
  }
}
`;
    }
}
exports.default = TemplateEngine;
