/*
* Autogenerated by Route Type Compiler (1.2.5)
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
/* tslint:disable */

import ApiDemots from '../server/route/api/demots';
import Demots from '../server/route/demots';

declare module 'test' {
  const apiDemots: ApiDemots;
  const demots: Demots;
  export interface IGetRoute {
    'api/demo/': ReturnType<typeof apiDemots.alive >;
    'api/demo/koa': ReturnType<typeof apiDemots.koa >;
    'api/demo/error/path/somepath': ReturnType<typeof apiDemots.error >;
    '/demo/': ReturnType<typeof demots.alive >;
    '/demo/koa': ReturnType<typeof demots.koa >;
    '/demo/error/path/somepath': ReturnType<typeof demots.error >
  }
  export interface IPostRoute {
    'api/demo/koa': ReturnType<typeof apiDemots.koaPost >;
    '/demo/koa': ReturnType<typeof demots.koaPost >
  }
}
